"""Initial migration.

Revision ID: 38632e58a93e
Revises: 
Create Date: 2024-07-07 20:34:55.106465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38632e58a93e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stripeCustomerId', sa.String(length=255), nullable=False),
    sa.Column('stripeSubscriptionId', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():

    op.drop_table('stripe_customer')
    # ### end Alembic commands ###
