"""empty message

Revision ID: 83f9c5bb1617
Revises: fcf2e7c5c7a5
Create Date: 2024-07-06 23:05:45.128326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f9c5bb1617'
down_revision = 'fcf2e7c5c7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    


def downgrade():
    op.drop_table('users')
    # ### end Alembic commands ###
