"""Create users table

Revision ID: fcf2e7c5c7a5
Revises: 1022759f7686
Create Date: 2024-07-06 22:45:27.292576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf2e7c5c7a5'
down_revision = '1022759f7686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('users')
    # ### end Alembic commands ###
